name: Build

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint ðŸ‘·
    steps:
      - name: Check out source code
        uses: actions/checkout@main

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: OpenTofu fmt
        run: tofu fmt -recursive -diff -check

      - name: OpenTofu Init
        if: always()
        id: init
        run: tofu init

      - name: OpenTofu Validate
        if: always()
        run: tofu validate
